<?php
session_start();

$conn = mysqli_connect("localhost", "root", "", "designwork");
if ($conn->connect_error) {
  die("Connection Failed: " . $conn->connect_error);
}

if (isset($_SESSION['profile_id'])) {
  $profile_id = $_SESSION['profile_id'];
} else {
  $profile_id = "";
}

// Query to fetch asset details based on the selected user
$sql = "SELECT EmpNo, name, designation, email, phone, work, assets, description, file_name, upload_on, TEmpNo, Tname, Tdesignation, Ttelephone, Temail
        FROM handover 
        WHERE EmpNo = '$profile_id'";

$result = $conn->query($sql);

if ($result->num_rows > 0) {
  $row = $result->fetch_assoc();

  $name = $row["name"];
  $designation = $row["designation"];
  $email = $row["email"];
  $phone = $row["phone"];
  $work = $row["work"];
  $assets = $row["assets"];
  $description = $row["description"];
  $file_name = $row["file_name"];
  $upload_on = $row["upload_on"];
  $taker_empno = $row["TEmpNo"];
  $taker_name = $row["Tname"];
  $taker_designation = $row["Tdesignation"];
  $taker_telephone = $row["Ttelephone"];
  $taker_email = $row["Temail"];

  $conn->close();

  // Generate the report HTML
  echo '<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <button class="print-button" onclick="printPage()">Print</button>
<button class="download-button" onclick="downloadReport()">Download</button>
  <title>Report</title>
  <style>
    @media print {
      @page {
        size: A4;
        margin: 0;
      }

      body {
        margin: 1.27cm;
      }
    }

    .form-container {
      width: 100%;
      max-width: 21cm;
      margin: 0 auto;
      padding: 2cm;
      border: 1px solid #000;
      background-color: #fff;
      box-sizing: border-box;
    }

    .header-image {
      text-align: center;
      margin-bottom: 1cm;
    }

    .header-image img {
      max-width: 100%;
      height: auto;
    }

    h2 {
      text-align: center;
      margin-bottom: 1cm;
    }

    .autogenerated-date {
      text-align: right;
      margin-bottom: 0.5cm;
      font-size: 12px;
    }

    table {
      width: 100%;
      padding: 0.5cm;
    }

    table tr {
      vertical-align: top;
    }

    table tr label {
      display: inline-block;
      font-weight: bold;
      margin-bottom: 0.3cm;
      width: 140px;
    }

    table tr span {
      display: inline-block;
    }

    input[type="submit"] {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 0.5cm;
      cursor: pointer;
      font-size: 16px;
    }
	
	table {
  width: 100%;
  padding: 0.1cm;
}

table tr {
  vertical-align: top;
}

table tr label {
  display: inline-block;
  font-weight: bold;
  margin-bottom: 0.3cm;
  width: 100px;
}

table tr span {
  display: inline-block;
}

.print-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}

.download-button {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
  </style>
  <script>
    window.onload = function() {
      var currentDate = new Date();
      var autogeneratedDateElement = document.getElementById("autogenerated-date");
      autogeneratedDateElement.innerHTML = currentDate.toDateString();
    };
    
    function downloadReport() {
      var htmlContent = document.documentElement.outerHTML;
      var blob = new Blob([htmlContent], { type: "text/html" });
      var url = URL.createObjectURL(blob);
      var a = document.createElement("a");
      a.href = url;
      a.download = "report.pdf";
      a.click();
      setTimeout(function() {
          URL.revokeObjectURL(url);
      }, 0);
  }
  </script>
</head>
<body>
  <div class="form-container">
  <script>
  function printPage() {
      window.print();
  }
</script>
    <div class="header-image">
      <img src="images/48f28e65-f195-4fe4-a5e0-e6533d6cfd84.jpg" alt="Header Image">
    </div>
    <h2><center>Handover Report</center></h2>
    <div class="autogenerated-date" id="autogenerated-date"></div>
    <form>
      <table>
        <tr>
          <td>
            <label>Name:</label> </td>
            <td><span>' . $name . '</span>
          </td>
          <td>
            <label>Designation:</label></td>
            <td><span>' . $designation . '</span>
          </td>
        </tr>
        <tr>
          <td>
            <label>Email:</label></td>
           <td> <span>' . $email . '</span>
          </td>
          <td>
            <label>Phone:</label></td>
            <td><span>' . $phone . '</span>
          </td>
        </tr>
        <tr>
          <td>
            <label>Work:</label></td>
            <td><span>' . $work . '</span>
          </td>
          <td>
            <label>Assets:</label></td>
            <td><span>' . $assets . '</span>
          </td>
        </tr>
        <tr>
          <td>
            <label>File Name:</label></td>
            <td><span>' . $file_name . '</span>
          </td>
          <td>
            <label>Upload On:</label></td>
           <td> <span>' . $upload_on . '</span>
          </td>
		  </tr>
		  <tr>
          <td>
            <label>Taker\'s EmpNo:</label></td>
            <td><span>' . $taker_empno . '</span>
          </td>
        
          <td>
            <label>Taker\'s Name:</label></td>
            <td><span>' . $taker_name . '</span>
          </td>
		  </tr>
		  <tr>
          <td>
            <label>Taker\'s Designation:</label></td>
            <td><span>' . $taker_designation . '</span>
          </td>
        
          <td>
            <label>Taker\'s Telephone:</label></td>
            <td><span>' . $taker_telephone . '</span>
          </td>
		  </tr>
		  <tr>
          <td>
            <label>Taker\'s Email:</label></td>
           <td> <span>' . $taker_email . '</span>
          </td>
		  </tr>
		      
      </table>
            <label>Description:</label>
            <span>' . $description . '</span>
     <br>
	 <br>
    </form>
  </div>
</body>
</html>';
} else {
  echo '<p>No Handover details found for the selected user.</p>';
  $conn->close();
}
?>